cap_medical_test/Order/urls.py
from django.urls import path
from Order.views import index_view, OrderAssignCreate, OrderStatusCreate, report_view

urlpatterns = [
    path('index/', index_view, name='operations'),
    path('report/', report_view, name='reports'),
    path('order_assign/<str:subgroup_name>', OrderAssignCreate, name='order_assign_create'),
    path('order_status/<str:subgroup_name>', OrderStatusCreate, name='order_status_create'),
    # path('order_assign/assign_to/', assign_orders, name='order_assign'),
]

cap_medical_test/cap_medical_test/urls.py
from django.contrib import admin
from django.urls import path, include
from Order.views import home_view, dashboard_view, s_view, RulesCreateView, RuleDeleteView, RuleEditView, \
    load_sub_groups, apply_rules
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

from Order.views import index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('Order.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', TemplateView.as_view(template_name='home.html')),
    # path('', LoginView.as_view()),
    path('', home_view),
    path('dashboard/', dashboard_view, name='dashboard'),
    # path('teamsettings/', s_view, name='teamsettings'),
    path('teamsettings/', s_view, name='teamsettings'),
    path('teamsettings/create/', RulesCreateView.as_view(), name='create_rules'),
    path('teamsettings/apply_rules/', apply_rules, name='apply_rules'),
    path('teamsettings/<int:id>/delete/', RuleDeleteView.as_view(), name='delete_rule'),
    path('teamsettings/<int:id>/edit/', RuleEditView.as_view(), name='edit_rule'),
    path('ajax/load-subgroups/', load_sub_groups, name='ajax_load_subgroups')
]

cap_medical_test/Order/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from datetime import date
from datetime import datetime
from django.db import models
from django.contrib.auth.models import Group,User
from myauth.models import SubGroup

class Teamsettings1(models.Model):
    main_group = models.ForeignKey(Group, on_delete=models.CASCADE)
    sub_group = models.OneToOneField(SubGroup, on_delete=models.CASCADE)
    sharewith = models.ManyToManyField(User,
                                       verbose_name='Assign To',
                                       limit_choices_to={'is_active': True, 'is_staff': False},
                                       related_name='share_withs'
                                       )
    columnsinclusions = models.TextField(blank=False, null=False, default='sales_order_number')
    description = models.TextField(max_length=255,blank=True, null=True, default=None)
    statusvalidation = models.TextField(blank=True, null=True)
    conditions = models.TextField(blank=True, null=True)

    def _get_status(self):
        pass


# class Salesorders(models.Model):
#     sales_order_number = models.TextField(db_column='Sales Order Number', primary_key=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_date_created = models.TextField(db_column='Sales Order Date Created', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_created_by = models.TextField(db_column='Sales Order Created by', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_branch_office = models.TextField(db_column='Sales Order Branch Office', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_status = models.TextField(db_column='Sales Order Status', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_manual_hold = models.TextField(db_column='Sales Order Manual Hold', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_location = models.TextField(db_column='Sales Order Location', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_discount_pct = models.TextField(db_column='Sales Order Discount Pct', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_po_number = models.TextField(db_column='Sales Order PO Number', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_purchase_order_number = models.TextField(db_column='Sales Order Purchase Order Number', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_reference = models.TextField(db_column='Sales Order Reference', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_previous_billing = models.TextField(db_column='Sales Order Previous Billing', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_next_billing = models.TextField(db_column='Sales Order Next Billing', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_user_1 = models.TextField(db_column='Sales Order User 1', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_user_2 = models.TextField(db_column='Sales Order User 2', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_user_3 = models.TextField(db_column='Sales Order User 3', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_user_4 = models.TextField(db_column='Sales Order User 4', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_confirm_date = models.TextField(db_column='Sales Order Confirm Date', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_confirmed_by = models.TextField(db_column='Sales Order Confirmed By', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_last_printed = models.TextField(db_column='Sales Order Last Printed', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_stop_date = models.TextField(db_column='Sales Order Stop Date', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_branch_group = models.TextField(db_column='Sales Order Branch Group', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_delivery_note = models.TextField(db_column='Sales Order Delivery Note', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_note = models.TextField(db_column='Sales Order Note', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_classification = models.TextField(db_column='Sales Order Classification', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_type = models.TextField(db_column='Sales Order Type', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_pod_order_status = models.TextField(db_column='Sales Order POD Order Status', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_manual_hold_reason = models.TextField(db_column='Sales Order Manual Hold Reason', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_facility = models.TextField(db_column='Sales Order Facility', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_facility_group = models.TextField(db_column='Sales Order Facility Group', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_retail_pos_order = models.TextField(db_column='Sales Order Retail POS Order', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_prior_system_key = models.TextField(db_column='Sales Order Prior System Key', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_height = models.TextField(db_column='Sales Order Height', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_weight = models.TextField(db_column='Sales Order Weight', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field1 = models.TextField(db_column='Sales Order Custom Fields Field1', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field2 = models.TextField(db_column='Sales Order Custom Fields Field2', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field3 = models.TextField(db_column='Sales Order Custom Fields Field3', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field4 = models.TextField(db_column='Sales Order Custom Fields Field4', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field5 = models.TextField(db_column='Sales Order Custom Fields Field5', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field6 = models.TextField(db_column='Sales Order Custom Fields Field6', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field7 = models.TextField(db_column='Sales Order Custom Fields Field7', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field8 = models.TextField(db_column='Sales Order Custom Fields Field8', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field9 = models.TextField(db_column='Sales Order Custom Fields Field9', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
#     sales_order_custom_fields_field10 = models.TextField(db_column='Sales Order Custom Fields Field10', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.

cap_medical_test/Order/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit
from django import forms
from datetime import datetime, timedelta

from django.contrib.auth.models import Group, User
from easy_select2 import Select2Multiple, Select2

from Order.models import Teamsettings1, SalesOrder_new, sales_order_assign
from myauth.models import SubGroup


class RulesCreate(forms.ModelForm):
    class Meta:
        model = Teamsettings1
        MY_COLS = [[i.name,]*2 for i in SalesOrder_new._meta.get_fields()]
        fields = '__all__'
        widgets = {
            # 'main_group' : forms.TextInput(),
            'sharewith' : forms.SelectMultiple(attrs={'class':'js-example-responsive'}),
            # 'sub_group' : forms.ModelChoiceField(queryset=Teamsettings1.objects.filter(maingroup=self.maingroup).select_related('sub_groups')),
            'columnsinclusions' : forms.SelectMultiple(attrs={'class':'js-example-responsive'}, choices=MY_COLS),
            'statusvalidation' : forms.TextInput(attrs={'cols': 80, 'rows': 20}),
            'description' : forms.TextInput(attrs={'cols': 80, 'rows': 20}),
            'salesorderclassification' : forms.Textarea(attrs={'rows': 4}),
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sub_group'].queryset = SubGroup.objects.none()
        if 'main_group' in self.data:
            try:
                main_group_id = int(self.data.get('main_group'))
                self.fields['sub_group'].queryset = SubGroup.objects.filter(main_group_id=main_group_id).order_by('name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            # main_group_id = int(self.data.get('main_group'))
            self.fields['sub_group'].queryset = SubGroup.objects.filter(main_group_id=int(self.instance.main_group_id)).order_by('name')
            # self.fields['sub_group'].queryset = self.instance.main_group.sub_group_set.order_by('name')

class FieldSet(object):
    pass


class CreateRules(forms.Form):
    MY_CHOICES = [(i.name,)*2 for i in SalesOrder_new._meta.get_fields()]
    MY_COLS = [[i.name,]*2 for i in SalesOrder_new._meta.get_fields()]
    MY_FUNCT = [('__contains', 'Contains'), ('__startswith', 'Starts With'), ('__endswith', 'Ends With'),
                ('__exact','Exact'), ('__iexact','Incasesensitive Exact'), ('__gt', 'Grater than'),
                ('__gte','Greate than Or Equal to'), ('__lt','Less than'), ('__lte','Less than Or Eqal to'),
                ('__isstartswith','Is Starts With'),('__gte = datetime.now() - timedelta(days = ','Before Days'),
                ('__gte = datetime.now() - timedelta(months = ', 'Before Months'),
                ('__gte = datetime.now() - timedelta(years = ', 'Before Years'),
                ('__isnull = True', 'IS NULL'), ('__isnull = False', 'IS NOT NULL')
                ]

    from django.contrib.auth.models import Group
    # main_grp_choices = [(i.name,)*2 for i in Group.objects.all()]
    # main_group = forms.ChoiceField(choices=main_grp_choices)
    # sharewith = forms.CharField(widget=forms.Textarea(attrs={'cols':40, 'rows':2}))
    # sub_group = forms.CharField(widget=forms.TextInput(attrs={'cols': 80, 'rows': 20}))
    # columnsinclusions = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs={'class':'js-example-responsive'}), choices=MY_CHOICES)
    # statusvalidation = forms.CharField(widget=forms.TextInput(attrs={'cols': 80, 'rows': 20}))
    columnlist = forms.ChoiceField(label='',choices=MY_CHOICES)
    functionlist = forms.ChoiceField(label='',choices=MY_FUNCT)
    matchvalue = forms.CharField(label='',widget=forms.TextInput())
    # salesorderclassification = forms.CharField(label='Generated Query',widget=forms.Textarea(attrs={'cols': 40, 'rows': 4}))


    class Meta:
        fieldsets = (
            ('Make a Query',{
                'fields': ('columnlist', 'functionlist', 'matchvalue')
            })
        )



class CreateOrderAssign(forms.ModelForm):
    class Meta:
        # STATUSVALIDATIONS = [(i,)*2 for i in Teamsettings1.objects.get(pk=SalesOrder_new.objects.get(pk=sales_order_number).rule_id).statusvalidation.split(',')]
        model = sales_order_assign
        fields = ['assign_to',]

    def __init__(self,subgroup_name, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.is_staff = kwargs.pop('is_staff', None)
        self.uid = kwargs.pop('uid', None)
        super().__init__(*args, **kwargs)
        if subgroup_name:
            try:
                if not self.is_staff:
                    self.fields['assign_to'].choices = [(None,'---------'),(self.uid,self.user),]
                else:
                    # id = Teamsettings1.objects.filter(sub_group__name=subgroup_name)
                    users = Teamsettings1.objects.filter(sub_group__name=subgroup_name).values('sharewith__id')
                    self.fields['assign_to'].queryset = User.objects.all().filter(id__in=users)
            except Exception as e:
                print(str(e))



class CreateOrderStatus(forms.ModelForm):
    class Meta:
        model = sales_order_assign
        fields = ['status',]

    def __init__(self,subgroup_name, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if subgroup_name:
            try:
                id = Teamsettings1.objects.filter(sub_group__name=subgroup_name)
                statusvalidations = id.values_list('statusvalidation',flat=True)
                temp = list([(i.strip(),)*2 for i in statusvalidations[0].split(',')])
                temp1 = [(None,'-----------')]
                temp1.extend(temp)
                self.fields['status'].choices = temp1
            except Exception as e:
                print(str(e))

cap_medical_test/Order/templates/Order/dashboard.html
{% extends 'base.html' %}

<head>
    <base target="a_iframe">
</head>

{% block content %}

<center>
<!--    <iframe width="1140" height="541.25" name="a_iframe"-->
<!--        src="http://example.com/"-->
<!--        frameborder="0" allowFullScreen="true"></iframe>-->

<!--    <iframe src="https://www.w3schools.com/"></iframe>-->
<iframe width="1140" height="541.25" name="a_iframe"
        src="https://app.powerbi.com/reportEmbed?reportId=f792268e-89c9-4d0c-b084-5b9b464a719a&autoAuth=true&ctid=935000e5-20b8-430a-949e-8319c10d5bdf&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXVzLW5vcnRoLWNlbnRyYWwtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQifQ%3D%3D"
        frameborder="0" allowFullScreen="true"></iframe>

    </center>
{% endblock %}

cap_medical_test/Order/templates/Order/index.html
{% extends 'base.html' %}

{% block content %}

<main role="main" class="container">
    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for Orders.." title="Type in Order Numbers">
    <input type="button" id="find" value="Find" class="btn-secondary"/>
    <div id="labels">
        <span id="current"></span>
        <span id="count"></span>
    </div>
    <div class="accordion" id="accordion2">
    {% for file,vals in resultset.items %}
        <h3 class="pt-4">{{ file }}</h3>
        <hr class="bg-secondary">
        {% for sheet,result in vals.items %}
          <div class="card mw-50" >
            <div class="card-header sticky-top bg-light">
              <h5 class="d-flex justify-content-between">
                  <div>
                    <a class="accordion-toggle" data-toggle="collapse" href="#collapse{{forloop.parentloop.counter}}{{forloop.counter}}" data-parent="#accordion2">
                        <div class="text-secondary">
                            {{sheet}}
                        </div>
                    </div>
                  <div class="d-flex justify-content-between">
                      <div>
                        <span class="d-sm-inline-flex text-right badge badge-dark badge-pill m-1" style="background-color: #004d40;">
                            {{ result|length }}
                        </span>
                      </div>
                    </a>
                      <div>
                      <form method="post">
                      {% if result|length > 0 %}
                                {% csrf_token %}
                              <input type="submit" class="btn btn-secondary btn-sm" value="Assign To" onclick="printChecked()" formaction="{% url 'order_assign_create' subgroup_name=sheet %}">
                              <input type="submit" class="btn btn-secondary btn-sm" value="Change Status" onclick="printChecked()" formaction="{% url 'order_status_create' subgroup_name=sheet %}">
<!--                            <a href="{% url 'order_assign_create' subgroup_name=sheet %}" id="OK" class="btn btn-secondary btn-sm" onclick="printChecked()">Ok</a>-->
<!--                            <input type="button" onclick="{% url 'order_assign_create' subgroup_name='{{sheet}}' %}" class="btn btn-secondary btn-sm" value="Ok"></input>-->
                        {% endif %}
                  </div></div>
<!--                  <div>-->
<!--                  </div>-->
              </h5>
            </div>

            <div id="collapse{{forloop.parentloop.counter}}{{forloop.counter}}" class="accordion-body collapse">
              <div class="card-body table-responsive" style="padding: 0px;">
                  <table class="table table-sm table-striped table-borderless table-hover" style="margin-bottom: 0;">
                    <thead class="thead-dark h-50">
                    {% if result %}
<!--                        <input type="button" value="Assign"/>-->

                        <th></th>
                        {% for c,r in result.0.items %}
                            {% if c == 'sales_order_assign__assign_to__username' %}
                                <th>Assigned_to</th>
                            {% elif c == 'sales_order_assign__status' %}
                                <th>Status</th>
                            {% else %}
                                <th>{{ c }}</th>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <th>No Data</th>
                    {% endif %}
                    </thead>

                  {% for i in result %}
                        <tr>
                            <td>
                                {% if i.sales_order_assign__assign_to__username == request.user.username or request.user.is_staff or i.sales_order_assign__assign_to__username == None %}
                                <input type="checkbox" name="sales_order_number" value="{{ i.sales_order_number }}"/>
                                {% endif %}
                            </td>
                        {% for k,v in  i.items %}
                            {% if v == None %}
                              <td> - </td>
                            {% else %}
                                {% if k == 'sales_order_number' %}
                                    <td>
                                        <a href="https://brightree.net/OrderEntry/frmSOOrderRO.aspx?SalesOrderKey={{ v }}&ShowAck=-1&Edit=0" target="_blank">{{ v }}</a>
                                    </td>
                                {% else %}
                                    <td>{{ v }}</td>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        </tr>
                  {% endfor %}
                </table>
                  </form>
              </div>
            </div>
          </div>
        {% endfor %}
    {% endfor %}
    </div>
</main>

<script type="text/javascript">
    function printChecked(){
		var items=document.getElementsByName('sales_order_number');
		var selectedItems="";
		for(var i=0; i<items.length; i++){
			if(items[i].type=='checkbox' && items[i].checked==true)
				selectedItems+=items[i].value+"\n";
		}
		document.getElementsByName('sales_order_number').value = selectedItems
<!--		alert(selectedItems);-->
	}
</script>


<script>
    function myFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementsByClassName("table");
        tr = [];
        for (a=0; a < table.length; i++) {
            tr += table[a].getElementsByTagName("tr");
        }
        window.alert(tr.length).show()
<!--        tr = table.getElementsByTagName("tr");-->

        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementByTagName("td")[2];
            if (td) {
            txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
</script>

{% endblock %}

cap_medical_test/Order/templates/Order/order_assign_create.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" action="./assign_to">
        {% csrf_token %}
        {{ form.as_p }}
        {{ order_numbers }}
        <input type="hidden" name="sales_orders" value="{{ order_numbers }}">
        <p>
            <input type="submit" value="OK">
        </p>
    </form>
{% endblock %}

cap_medical_test/Order/templates/Order/order_status.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="sales_orders" value="{{ order_numbers }}">
        {{ order_numbers }}
        <p>
            <input type="submit" value="OK">
        </p>
    </form>
{% endblock %}

cap_medical_test/Order/templates/Order/rule_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <h1>
            Do You Want to delete the rule {{ object.id }}?
        </h1>
        <p>
            <input type="submit" value="Yes" />
            <a href="{% url 'teamsettings' %}">Cancel</a>
        </p>
    </form>

{% endblock %}

cap_medical_test/Order/templates/Order/rule_edit.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <input type="submit" value="Yes" />
            <a href="{% url 'teamsettings' %}">Cancel</a>
        </p>
    </form>


<script type="text/javascript">
$(".js-example-responsive").select2({
    width: 'resolve' // need to override the changed default
});
</script>


{% endblock %}

cap_medical_test/Order/templates/Order/rules_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <form method="post" id="RulesCreateForm" data-subgroups-url="{% url 'ajax_load_subgroups' %}" novalidate>
        {% csrf_token %}
<!--        {{ form|crispy }}-->

        {{ form.main_group|as_crispy_field }}
        {{ form.sub_group|as_crispy_field }}
        {{ form.sharewith|as_crispy_field }}
        {{ form.columnsinclusions|as_crispy_field }}
        {{ form.description|as_crispy_field }}
        {{ form.statusvalidation|as_crispy_field }}

        <div class="form-row">
            <div>
               <h6>Add Filters</h6>
            </div>
        </div>
        <fieldset>
            <legend><label>Filters</label></legend>
            <div class="form-row">
                <div class="form-group col-md-5 mb-0">
                    {{ form2.columnlist|as_crispy_field }}
                </div>
                 <div class="form-group col-md-3 mb-0">
                    {{ form2.functionlist|as_crispy_field }}
                </div>
                <div class="form-group col-md-3 mb-0">
                    {{ form2.matchvalue|as_crispy_field }}
                </div>
                <input type="Button" value="Add" class="form-group col-md-1 mb-3" onclick="add_filter()">
            </div>
        </fieldset>


        <div class="form-row">
            <input type="Button" value="AND" onclick="update_AND()" class="form-group col-md-6 mb-3"/>
            <input type="Button" value="OR" onclick="update_OR()" class="form-group col-md-6 mb-3"/>
        </div>

        {{ form.conditions|as_crispy_field }}

        <center><button type="submit">Submit </button></center>
    </form>

    <p id="demo"></p>



<script>
    function update_AND(){
    var elem = document.getElementById('id_conditions');
    var old  = elem.value;
    elem.value = old +' '+ 'AND' ;
}


    function update_OR(){
    var elem = document.getElementById('id_conditions');
    var old  = elem.value;
    elem.value = old +' '+ 'OR' ;
}


    function add_filter(){
    var columnlist =  document.getElementById('id_columnlist').value
    var functionlist =  document.getElementById('id_functionlist').value
    if (functionlist.includes('timedelta')) {
        var matchval =  document.getElementById('id_matchvalue').value
        var elem = document.getElementById('id_conditions');
        var old  = elem.value;
        elem.value = old +' '+'Q('+ columnlist +' '+ functionlist +matchval +'))';
    } else if(functionlist.includes('isnull')){
        var elem = document.getElementById('id_conditions');
        var old  = elem.value;
        elem.value = old +' '+'Q('+ columnlist + functionlist +')'
    }
    else {
        var matchval =  document.getElementById('id_matchvalue').value
        var elem = document.getElementById('id_conditions');
        var old  = elem.value;
        elem.value = old +' '+'Q('+ columnlist + functionlist +'='+ matchval +')' ;
    }
}

</script>

<script type="text/javascript">
$(".js-example-responsive").select2({
    width: 'resolve' // need to override the changed default
});
</script>




<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
$("#id_main_group").change(function () {
  var url = $("#RulesCreateForm").attr("data-subgroups-url");  // get the url of the `load_cities` view
  var main_group_id = $(this).val();  // get the selected country ID from the HTML input

  $.ajax({                       // initialize an AJAX request
    url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
    data: {
      'main_group': main_group_id       // add the country id to the GET parameters
    },
    success: function (data) {   // `data` is the return of the `load_cities` view function
      $("#id_sub_group").html(data);  // replace the contents of the city input with the data that came from the server
    }
  });

});
</script>

{% endblock %}